version: "3"
services:
  web:
    image: elixir
    volumes:
      - .:/code
    working_dir: /code
    command: mix do local.hex --force, phx.server
    depends_on:
      - db
    network_mode: host
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estacionamento_ifro
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
